language: rust
rust:
  - nightly

before_script:
  - rustup component add rustfmt-preview
  - cargo clean

script:
  # Check formatting
  - cargo fmt --all -- --check
  - cargo build --verbose --all
  - cargo test --verbose --all
