language: rust
rust:
  - stable
  - nightly
  - 1.31.0
  - 1.31.1
  - 1.32.0
  - 1.33.0
  - 1.34.0
  - 1.35.0
  - 1.36.0
  - 1.37.0
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
