[package]
name = "etcd-rs"
version = "0.1.1"
authors = ["ccc13 <currantxx@gmail.com>"]
edition = "2018"
repository = "https://github.com/ccc13/etcd-rs"
description = "etcd client for rust"
license = "MIT"

[dependencies]
grpcio = "0.4"
futures = "^0.1.15"
protobuf =  "2.0"

[dev-dependencies]
tokio = "0.1.15"
