[package]
name = "etcd-rs"
version = "0.2.0-alpha.2"
authors = ["ccc13 <currantxx@gmail.com>"]
edition = "2018"
keywords = ["etcd", "future"]
repository = "https://github.com/ccc13/etcd-rs"
homepage = "https://github.com/ccc13/etcd-rs"
description = "etcd client for rust"
documentation = "https://docs.rs/etcd-rs"
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[dependencies]
tonic = { version = "=0.1.0-alpha.6" }
bytes = "0.4"
prost = "0.5"
prost-derive = "0.5"
tokio = "0.2.0-alpha.6"
async-stream = "0.1.2"

[dev-dependencies]

[build-dependencies]
tonic-build = "=0.1.0-alpha.6"
